version: '3.8'

services:
  # Base de donn√©es MySQL
  mysql:
    build: ./database
    container_name: mysql
    environment:
      MYSQL_DATABASE: devsecopsdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devsecops
      MYSQL_PASSWORD: devsecops
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devsecops-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Spring Boot
  backend:
    build: ./Backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devsecopsdb
      SPRING_DATASOURCE_USERNAME: devsecops
      SPRING_DATASOURCE_PASSWORD: devsecops
      SERVER_PORT: 8089
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - devsecops-network
    restart: on-failure

  # Frontend Angular
  frontend:
    build: ./Front
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - devsecops-network

networks:
  devsecops-network:
    driver: bridge

volumes:
  mysql-data:
